server:
  servlet:
    session:
      cookie:
        name: FLOWDEVSESSIONID
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 30
    minimumIdle: 5
    hikari:
      connection-test-query: SELECT 1

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        dialect: org.hibernate.dialect.MySQL57Dialect

  jackson:
    time-zone: "Asia/Seoul"

  thymeleaf:
    prefix=classpath: templates/
    suffix: .html
    check-template-location: true
    cache: false

  main:
    allow-bean-definition-overriding: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
